### ISSUE TITLE
Server's .env file is public

### ISSUE THREAD

**Issue by Tocutoeltuco** [FIN-18-20/RubiksMind#37]
I'm pretty sure `.env` files are meant to be kept private... [it's not the case here!](https://github.com/FIN-18-20/RubiksMind/blob/155a74a77dfacc6d76dade2d7287451f8c0050e4/server/.env) I recommend adding it to .gitignore.

**Comment by vkaelin** [comment]
Done, thanks! It was some useless data but thanks anyway ! 💙

**Comment by Lothindir** [comment]
Yes thanks. The .env was already added to the .gitignore, but we forgot to remove it from the repo.
