### ISSUE TITLE
Sign Out process (& profiles)

### ISSUE THREAD

**Issue by athanasiab** [FIN-18-20/RubiksMind#55]
When signing out, the page doesn't refresh and you can still see the account's information (when in profile page). 
I found out that you can also access other profiles' information by adding at the homepage link "/profile/*username*". 
I didn't know if that was on purpose so, I though I could mention it.

Example
![sign out](https://user-images.githubusercontent.com/46161935/135146363-55184198-9e04-4612-aaf4-d934bf2aae6e.png)
:

**Comment by vkaelin** [comment]
Yeah it's on purpose. All profiles are public but thanks for the interest !
